[build]
  publish = "dist/"
  command = "gulp build"

[template.environment]
  MY_ACCOUNT_ID = "Account ID for tracking code"
  MY_SITE_NAME = "Site name"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"